ct_root_path: ../data/verse2020_test
dataset_path: ../data/verse2020_test_detection_dataset
dataset_images_path: ../data/verse2020_test_detection_dataset/images
dataset_masks_path: ../data/verse2020_test_detection_dataset/masks
dataset_json_path: ../data/verse2020_test_detection_dataset/detection_data.json

projection_parameter:
  sdr: 500
  height: 512
  specific_height_list: {"luyu": 500, "shuailei": 1000}
  delx: 1
  threshold: 0
  AP_num_samples: 2
  LA_num_samples: 2
  AP_rot_range_list: [[75, 105], [165, 195], [165, 195]]
  AP_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  LA_rot_range_list: [[75, 105], [165, 195], [75, 105]]
  LA_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  # AP_rot_range_list: [[90, 90], [180, 180], [180, 180]]
  # AP_trans_range_list: [[0, 0], [0, 0], [0, 0]]
  # LA_rot_range_list: [[90, 90], [180, 180], [90, 90]]
  # LA_trans_range_list: [[0, 0], [0, 0], [0, 0]]
  AP_bbox_label_type: big
  LA_bbox_label_type: big
  min_bbox_percentage_of_height: 0.05


vis_parameter:
  is_vis: True
  vis_save_path: data/verse2020_test_detection_dataset/bbox_vis
  rotation_bbox_vis_save_path: data/verse2020_test_detection_dataset/rotation_bbox_vis # 旋转框可视化